######################################################################
#  Project Makefile
######################################################################

BINARY		= main
SRCFILES	= $(shell find -name *.c)
LDSCRIPT	= stm32f103c8t6.ld
TGT_CFLAGS += -I./sys -I.
TGT_CXXFLAGS += -I./sys -I.

all:
	@echo $(SCRFILES)
